### ISSUE TITLE
Problem installing add-ins

### ISSUE THREAD

**Issue by BarneyLabstep** [PerkinElmer/ChemDraw-AddIns#14]
I'm using ChemDraw Professional for Mac (v 18.0.0.231 (4318)).

I tried downloading the Examples in this repo.

If I install the '.chemdrawaddin' files directly via the Add-in Manager it works but if I try and zip the individual folders and change the extension to '.chemdrawaddin' I get the message

```
The "chemdraw-addin-metadata.json" package file is either missing or cannot be recognized as JSON format.
```

**Comment by abhimanyusirohi** [comment]
This happens if you zip the folder. Try selecting the files, right-click and select `Compress x Items` from the menu and rename extension to `chemdrawaddin`.

**Comment by BarneyLabstep** [comment]
Thanks for the quick response, this has solved the issue!
